---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/data/sample123.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
     - name: Change file ownership, group and permissions
       ansible.builtin.file:
         path: ~/data/sample123.txt
         owner: root
         group: root
         mode: '0664'
    
