---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/example.txt"
  tasks:
  - name: Ansible lineinfile insert after example
    lineinfile:
      dest: "~/example.txt"
      line: '/dev/sdd1   ext4     1     2'
      insertbefore: '#librariy]'    
  - name: Ansible lineinfile insertbefore example
    lineinfile:
      dest: "~/example.txt"
      line: 'inventory = /home/mdtutorials/inventory.ini'
      insertbefore: '#library'
   
     
