---
- name: file module demo
  hosts: all
  remote_user: root
  become: true
  vars:
    myfile: "~/example.txt"
    dir: "~/data1"
    dir2: "/new/data2"
    dir3: "/data3"
  tasks:
    - name: Creating an file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
    - name: Creating an data1
      shell: sudo mkdir /data5
      args:
        executable: /home/ec2-user
      
        
        
      
      
