---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/data/sample123.txt"
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: ~/data2
        state: directory
    - name: mount partions
      become: true
      become_user: root
      mount:
        path: ~/data2
        src: /dev/xvda1
        fstype: ext4
        state: mounted
     
