---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/data/sample123.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
     - name: Recursively change ownership of a directory
       ansible.builtin.file:
         path: ~/data1
         state: directory
         recurse: yes
         owner: root
         group: foo
     - name: Remove file (delete file)
       ansible.builtin.file:
         path: ~/data/sample123.txt
         state: absent
     - name: Recursively remove directory
       ansible.builtin.file:
         path: ~/data1
         state: absent
