---
- name: file module demo
  hosts: all
  vars:
    item: "/etc"
    myfile: "sample.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
         mode: u=rwx,g=rwx,o=rwx
         owner: test
         group: test
     - name: Creating a file with content
       copy:
         dest: "~/sample.txt"
         content: |
           This is My Sample test file
     - name: Ansible copy file to remote server
       copy:
         src: ~/sample.txt
         dest: /tmp 
     - name: Create multiple files
       file: 
         path: "{{ item }}"
         state: touch
       with_items:
       - test01.txt
       - test02.txt
       - test03.txt
       - test04.txt
     
     
     
      
    
        
        
      
      
