---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/data/sample123.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
     - name: Set access time based on seconds from epoch value
       ansible.builtin.file:
         path: ~/data/sample123.txt
         state: file
         access_time: '{{ "%Y%m%d%H%M.%S" | strftime(stat_var.stat.atime) }}'
