---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/example.txt"
    dir: "~/data2"
    mount_src: "/dev/xvda1"
    mount_path: "/data4"
  tasks:
    - name: Creating an file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
    - name: Creating an data1
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
    - name: Create File System
      filesystem:
        fstype: ext4
        dev: "{{ mount_src }}"
    - name: Mount File System
      mount:
        path: "{{ mount_path }}"
        src: "{{ mount_src }}"
        fstype: ext4
        state: mounted
        
        
      
      
