---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/example.txt"
    dir: "~/data2"
  tasks:
    - name: Creating an file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
    - name: Creating an data1
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
    - name: make create directory
      command: sudo mkdir /data4
      become: true
      become_user: root
    - name: mount partitions
      mount: 
        path: /data4
        src: /dev/xvda1
        fstype: ext4
        state: mounted
        
        
      
      
