---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/example.txt"
    dir: "~/data2"
    mount_src: "/dev/xvda1"
    mount_path: "/data4"
  tasks:
    - name: Creating an file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
    - name: Creating an data1
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
    - name: make mount  data directory
      command: sudo mount /dev/xvda1 /data4
      become: true
      become_user: root
    
        
        
      
      
