---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/example.txt"
  tasks:
  - name: Ansible lineinfile insert after example
    lineinfile:
      dest: "~/example.txt"
      line: '/dev/sdc1   ext4     1     2'
      insertafter: '\[defaults\]'    
  - name: Removing a file
    file:
      path: "/sample123.txt"
      state: absent
   
     
