---
- name: file module demo
  hosts: all
  remote_user: root
  vars:
    myfile: "~/example.txt"
    dir: "~/data1"
    dir2: "/new/data2"
    dir3: "/data3"
  tasks:
   - name: sudo without password for root group
     copy:
       content: 'root ALL=(ALL:ALL) NOPASSWD:ALL'
       dest: /home/ec2-user/data1/sudoers123
    - name: Creating an file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
    - name: Creating an data1
      ansible.builtin.file:
        path: "{{ dir3 }}"
        state: directory
        
        
      
      
