---
- name: file module demo
  hosts: all
  vars:
    item: "/home/ec2-user/data"
    myfile: "sample.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
         mode: 0774
     - name: Creating a file with content
       copy:
         dest: "~/sample.txt"
         content: |
           This is My Sample test file
     - name: Ansible copy file to remote server
       copy:
         src: /home/ec2-user/sample.txt
         dest: /home/ec2-user/data2
         remote_src: yes
     - name: Create multiple files
       file: 
         path: "{{ item }}"
         state: touch
       with_items:
       - test01.txt
       - test02.txt
       - test03.txt
       - test04.txt
       loop_control:
        loop_var: outer_item
     
     
     
      
    
        
        
      
      
