---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/example.txt"
  tasks:
  - name: Creating a file with content
    copy:
      dest: "~/example.txt"
      content: |
        line 01
        line 02
        lone 01
        lone 02
  - name: Ansible lineinfile insert after example
    lineinfile:
      dest: "~/example.txt"
      line: 'inventory = /home/fedora/inventory.ini'
      insertafter: '\[defaults\]'    
  - name: Removing a file
    file:
      path: "/sample123.txt"
      state: absent
   
     
