---
- name: file module demo
  hosts: all
  remote_user: root
  become: true
  vars:
    myfile: "~/example.txt"
    dir: "~/data1"
    dir2: "/new/data2"
    dir3: "/data3"
  tasks:
    - name: Creating an file
      ansible.builtin.file:
        path: "{{ myfile }}"
        state: touch
    - name: Creating an data1
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
    - name: make create directory
      command: sudo mkdir /data3
      become: true
      become_user: root
      
        
        
      
      
