---
- name: Disk Partions
  hosts: all
  
  tasks:
    - name: Mount Partition
      mount:
         path: /Mongodb
         src: /dev/xvda1
         fstype: ext4
         state: mounted
      
      
