---
- name: file module demo
  hosts: all
  vars:
    myfile: "sample123.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
    
