---
- name: file module demo
  hosts: all
  vars:
    item: "~/data"
    myfile: "sample.txt"
  tasks:
     - name: Creating an file
       ansible.builtin.file:
         path: "{{ myfile }}"
         state: touch
     - name: "change owner permissions on the sample.txt file"
       command: sudo chown root:root sample.txt
       become: true
       become_user: root
     - name: Creating a file with content
       copy:
         dest: "~/sample.txt"
         content: |
           This is My Sample test file
     - name: Ansible copy file to remote server1
       copy:
         src: /home/ec2-user/sample.txt
         dest: /home/ec2-user/data2
         remote_src: yes
     - name: Create multiple files
       file: 
         path: "{{ item }}"
         state: touch
       with_items:
       - test01.txt
       - test02.txt
       - test03.txt
       - test04.txt
       loop_control:
        loop_var: outer_item
     - name: Ansible copy file to remote server2
       copy:
         src: /home/ec2-user/
         dest: /home/ec2-user/data
         remote_src: yes
         mode: 0777
       with_fileglob:
       - ~/test*
     
     
     
      
    
        
        
      
      
