---
- name: file module demo
  hosts: all
  vars:
    myfile: "~/data/sample123.txt"
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: ~/data2
        state: directory
        mode: '0755'
     
